#!/usr/bin/env node
/**
 * generate.js — 读取每本书的 catalog.md 生成数据文件
 *
 * catalog.md 格式：
 * | 编号 | 篇名 | 路径 | 状态 |
 * 状态为"已解读"且路径存在时，提取 tutorial.md 内容
 * 其他均为 isDone: false
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { marked } from 'marked';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = '/root/.hermes/mingli';
const OUT_DIR = path.join(__dirname, '../src/data');

marked.setOptions({ gfm: true, breaks: false });

function parseMarkdown(md) {
  if (!md) return '';
  const clean = md.replace(/^---[\s\S]*?---\n/, '').trim();
  return String(marked.parse(clean));
}

function parseCatalog(catalogPath) {
  const content = fs.readFileSync(catalogPath, 'utf-8');
  const rows = [];
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    // 跳过 markdown 标题行（# 开头，含 h1/h2/h3）
    if (/^#{1,6}\s/.test(trimmed)) continue;
    if (trimmed.match(/^\|[-\s:|]+\|$/)) continue;
    const cells = trimmed.split('|').map(c => c.trim()).filter(c => c !== '');
    if (cells.length < 3) continue;
    const num = cells[0];
    const status = cells[cells.length - 1];
    if (!/^\d+$/.test(num)) continue;
    rows.push({
      num,
      title: cells[1],
      filePath: cells.length > 2 ? cells[2] : '',
      status,
    });
  }
  return rows;
}

function getBookTitle(metaPath) {
  if (!fs.existsSync(metaPath)) return null;
  const content = fs.readFileSync(metaPath, 'utf-8');
  const m = content.match(/《([^》]+)》/);
  return m ? m[1] : null;
}

const BOOK_DIRS = fs.readdirSync(ROOT).filter(f => {
  const p = path.join(ROOT, f);
  return fs.statSync(p).isDirectory() &&
         fs.existsSync(path.join(p, 'catalog.md')) &&
         fs.existsSync(path.join(p, 'skills'));
});

const books = [];

for (const bookSlug of BOOK_DIRS) {
  const bookRoot = path.join(ROOT, bookSlug);
  const catalogPath = path.join(bookRoot, 'catalog.md');
  const metaPath = path.join(bookRoot, 'meta/index.md');
  const skillsDir = path.join(bookRoot, 'skills');

  // 标题
  const title = getBookTitle(metaPath) || bookSlug;

  // 解析篇章总表
  const catalogRows = parseCatalog(catalogPath);

  // 生成篇章列表 + 已解读内容
  const chapters = [];
  const chaptersData = {};

  for (const row of catalogRows) {
    const isDone = row.status === '已解读' && row.filePath && row.filePath.length > 0;
    chapters.push({ num: row.num, name: row.title, isDone });

    if (isDone) {
      const fullPath = path.join(bookRoot, row.filePath);
      if (fs.existsSync(fullPath)) {
        const content = fs.readFileSync(fullPath, 'utf-8');
        chaptersData[row.title] = parseMarkdown(content);
      }
    }
  }

  // 读取技能
  const skillsData = {};
  if (fs.existsSync(skillsDir)) {
    for (const entry of fs.readdirSync(skillsDir)) {
      const skillPath = path.join(skillsDir, entry, 'SKILL.md');
      if (fs.existsSync(skillPath)) {
        const content = fs.readFileSync(skillPath, 'utf-8');
        skillsData[entry] = parseMarkdown(content);
      }
    }
  }

  const doneCount = chapters.filter(c => c.isDone).length;

  books.push({
    slug: bookSlug,
    title,
    total: chapters.length,
    done: doneCount,
    chapters,
    chaptersData,
    skillsData,
  });
}

// 生成 books.ts
const bookData = books.map(b => ({
  slug: b.slug,
  title: b.title,
  total: b.total,
  done: b.done,
  chapters: b.chapters,
  skills: Object.keys(b.skillsData).sort((a, bb) => a.localeCompare(bb, 'zh')).map(name => ({ name })),
}));

const booksTs = `// Auto-generated by scripts/generate.js — do not edit manually
export interface ChapterInfo {
  num: string;
  name: string;
  isDone: boolean;
}

export interface Book {
  slug: string;
  title: string;
  total: number;
  done: number;
  chapters: ChapterInfo[];
  skills: { name: string }[];
}

export const books: Book[] = ${JSON.stringify(bookData, null, 2)};
`;

// 生成 per-book 内容文件
let exports = '// Auto-generated — do not edit manually\n';

for (const book of books) {
  const filePath = path.join(OUT_DIR, `${book.slug}.ts`);
  const interpJson = JSON.stringify(book.chaptersData, null, 2);
  const skillJson = JSON.stringify(book.skillsData, null, 2);
  const content = `// Auto-generated — do not edit manually
export const interpContent: Record<string, string> = ${interpJson};
export const skillContent: Record<string, string> = ${skillJson};
`;
  fs.writeFileSync(filePath, content);
  exports += `export * from './${book.slug}';\n`;
}

fs.writeFileSync(path.join(OUT_DIR, 'books.ts'), booksTs);
fs.writeFileSync(path.join(OUT_DIR, 'index.ts'), exports);

console.log(`Generated ${books.length} book(s):`);
for (const b of books) {
  console.log(`  ${b.slug}: total=${b.total}, done=${b.done}`);
  console.log(`    chapters: ${b.chapters.filter(c=>c.isDone).map(c=>c.name).join(', ')}`);
}
console.log('Done.');