// Auto-generated by scripts/generate.js — do not edit manually
import type { Book } from './book-types';

export const books: Book[] = [
  {
    "slug": "渊海子平",
    "section": "命",
    "category": "八字",
    "title": "渊海子平",
    "author": "[宋] 徐大升 编纂",
    "version": "据通行本（渊海/渊源合编本）",
    "description": "子平命理学开山之作，五卷汇编体，涵盖干支五行、十神格局、六亲赋文、诗诀口诀，共三百余篇",
    "total": 245,
    "done": 0,
    "chapters": [
      {
        "num": "01",
        "name": "题记与引",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "02",
        "name": "论五行所生之始",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "03",
        "name": "论天地干支所出",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "04",
        "name": "天干相合",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "05",
        "name": "十干所属方位十二支所属论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "06",
        "name": "论十二地支阴阳所属",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "07",
        "name": "论十二支六合",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "08",
        "name": "论十二支三合",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "09",
        "name": "论十二支相冲",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "10",
        "name": "论十二支相穿",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "11",
        "name": "论十二支相刑",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "12",
        "name": "论干支字义",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "13",
        "name": "论六十花甲子纳音并注解",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "14",
        "name": "论天干生旺死绝",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "15",
        "name": "天干五阳通变",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "16",
        "name": "天干五阴通变",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "17",
        "name": "论年上起月例",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "18",
        "name": "论日上起时例",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "19",
        "name": "论起玉堂天乙贵人",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "20",
        "name": "论三奇贵人",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "21",
        "name": "论月德贵人",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "22",
        "name": "论天德贵人",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "23",
        "name": "论三元",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "24",
        "name": "论十干禄",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "25",
        "name": "论驿马",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "26",
        "name": "论天赦",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "27",
        "name": "论华盖",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "28",
        "name": "论六甲空亡",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "29",
        "name": "论四大空亡",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "30",
        "name": "论天罗地网",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "31",
        "name": "论羊刃",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "32",
        "name": "论起大运法",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "33",
        "name": "论行小运法",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "34",
        "name": "论五行相生相克",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "35",
        "name": "论天地干支暗藏总诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "36",
        "name": "地支藏遁歌",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "37",
        "name": "论日为主",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "38",
        "name": "论月令",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "39",
        "name": "论生旺",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "40",
        "name": "又论五行生旺衰绝吉凶",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "41",
        "name": "论五行墓库财印",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "42",
        "name": "论官杀混杂要制伏",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "43",
        "name": "论五行生克制化各有所喜所害例",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "44",
        "name": "子平举要歌",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "45",
        "name": "详解定真论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷一 · 基础理论"
      },
      {
        "num": "46",
        "name": "喜忌篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "47",
        "name": "继善篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "48",
        "name": "正官论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "49",
        "name": "论官星太过",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "50",
        "name": "论偏官即七杀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "51",
        "name": "论七杀即偏官",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "52",
        "name": "论印绶",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "53",
        "name": "论正财",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "54",
        "name": "论偏财",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "55",
        "name": "论食神",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "56",
        "name": "论倒食",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "57",
        "name": "论伤官",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "58",
        "name": "论劫财",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "59",
        "name": "论羊刃",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "60",
        "name": "论刑合",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "61",
        "name": "论福德秀气",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "62",
        "name": "论杂气",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "63",
        "name": "论日贵",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "64",
        "name": "论日德",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "65",
        "name": "论日刃",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "66",
        "name": "论魁罡",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "67",
        "name": "论金神",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "68",
        "name": "论时墓",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "69",
        "name": "正官格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "70",
        "name": "杂气财官格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "71",
        "name": "月上偏官格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "72",
        "name": "时上偏财格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "73",
        "name": "时上一位贵格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "74",
        "name": "飞天禄马格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "75",
        "name": "倒冲格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "76",
        "name": "六乙鼠贵格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "77",
        "name": "合禄格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "78",
        "name": "子遥巳格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "79",
        "name": "壬骑龙背格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "80",
        "name": "井栏叉格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "81",
        "name": "归禄格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "82",
        "name": "六阴朝阳格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "83",
        "name": "刑合格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "84",
        "name": "拱贵格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "85",
        "name": "拱禄格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "86",
        "name": "印绶格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "87",
        "name": "杂气印绶格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "88",
        "name": "六壬趋艮格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "89",
        "name": "六甲趋干格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "90",
        "name": "勾陈得位格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "91",
        "name": "玄武当权格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "92",
        "name": "炎上格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "93",
        "name": "润下格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "94",
        "name": "从革格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "95",
        "name": "稼穑格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "96",
        "name": "曲直格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "97",
        "name": "日德秀气格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "98",
        "name": "弃命从财格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "99",
        "name": "伤官生财格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "100",
        "name": "弃命从杀格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "101",
        "name": "伤官带杀格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "102",
        "name": "岁德扶杀格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "103",
        "name": "岁德扶财格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "104",
        "name": "夹丘格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "105",
        "name": "两干不杂格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "106",
        "name": "五行俱足格",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "107",
        "name": "天元一气",
        "isDone": false,
        "hasSkill": false,
        "category": "卷二 · 格局十神"
      },
      {
        "num": "108",
        "name": "六亲总论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "109",
        "name": "六亲捷要歌",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "110",
        "name": "论父",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "111",
        "name": "论母",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "112",
        "name": "论妻妾",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "113",
        "name": "论兄弟姐妹",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "114",
        "name": "论子息",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "115",
        "name": "论妇人总诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "116",
        "name": "阴命赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "117",
        "name": "女命富贵贫贱篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "118",
        "name": "论小儿",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "119",
        "name": "论小儿关杀例",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "120",
        "name": "论性情",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "121",
        "name": "论疾病",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "122",
        "name": "论大运",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "123",
        "name": "论太岁吉凶",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "124",
        "name": "论运化气",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "125",
        "name": "化气十段锦",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "126",
        "name": "神趣八法-类象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "127",
        "name": "神趣八法-属象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "128",
        "name": "神趣八法-从象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "129",
        "name": "神趣八法-化象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "130",
        "name": "神趣八法-照象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "131",
        "name": "神趣八法-返象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "132",
        "name": "神趣八法-鬼象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "133",
        "name": "神趣八法-伏象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "134",
        "name": "杂论口诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "135",
        "name": "群兴论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "136",
        "name": "论兴亡",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "137",
        "name": "宝法第一",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "138",
        "name": "宝法第二",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "139",
        "name": "寸金搜髓论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "140",
        "name": "论命细法",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "141",
        "name": "伤官说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "142",
        "name": "心镜歌",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "143",
        "name": "妖祥赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "144",
        "name": "络绎赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "145",
        "name": "相心赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "146",
        "name": "玄机赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "147",
        "name": "幽微赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "148",
        "name": "五行元理消息赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷三 · 六亲进阶"
      },
      {
        "num": "149",
        "name": "金玉赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "150",
        "name": "碧渊赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "151",
        "name": "造微论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "152",
        "name": "人鉴论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "153",
        "name": "爱憎赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "154",
        "name": "万金赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "155",
        "name": "掣要捷驰玄妙诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "156",
        "name": "渊源集说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "157",
        "name": "子平百章歌",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "158",
        "name": "四言独步",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "159",
        "name": "身弱论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "160",
        "name": "弃命从杀论",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "161",
        "name": "五言独步",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "162",
        "name": "十干体象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "163",
        "name": "十二支体象",
        "isDone": false,
        "hasSkill": false,
        "category": "卷四 · 赋文精要"
      },
      {
        "num": "164",
        "name": "正官诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "165",
        "name": "偏官诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "166",
        "name": "印绶诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "167",
        "name": "正财诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "168",
        "name": "偏财诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "169",
        "name": "食神诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "170",
        "name": "伤官诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "171",
        "name": "羊刃诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "172",
        "name": "刑合诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "173",
        "name": "日贵诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "174",
        "name": "金神诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "175",
        "name": "日德诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "176",
        "name": "魁罡诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "177",
        "name": "时墓诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "178",
        "name": "杂气财官诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "179",
        "name": "时上偏财诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "180",
        "name": "时上一位贵诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "181",
        "name": "飞天禄马诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "182",
        "name": "六乙鼠贵诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "183",
        "name": "合禄诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "184",
        "name": "子遥巳诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "185",
        "name": "壬骑龙背诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "186",
        "name": "井栏叉格诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "187",
        "name": "归禄格诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "188",
        "name": "六阴朝阳诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "189",
        "name": "拱禄拱贵诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "190",
        "name": "六甲趋干诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "191",
        "name": "六壬趋艮诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "192",
        "name": "勾陈得位诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "193",
        "name": "玄武当权诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "194",
        "name": "润下诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "195",
        "name": "从革诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "196",
        "name": "稼穑诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "197",
        "name": "曲直格诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "198",
        "name": "炎上格诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "199",
        "name": "福德格诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "200",
        "name": "弃命从财诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "201",
        "name": "弃命从杀诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "202",
        "name": "杀重有救诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "203",
        "name": "天元一气诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "204",
        "name": "化气诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "205",
        "name": "刑冲诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "206",
        "name": "克妻诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "207",
        "name": "克子诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "208",
        "name": "运晦诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "209",
        "name": "运通诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "210",
        "name": "带疾诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "211",
        "name": "寿元诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "212",
        "name": "飘荡诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "213",
        "name": "女命诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "214",
        "name": "长生诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "215",
        "name": "沐浴诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "216",
        "name": "冠带诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "217",
        "name": "临官诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "218",
        "name": "帝旺诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "219",
        "name": "衰病死诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "220",
        "name": "墓库诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "221",
        "name": "胞胎诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "222",
        "name": "胎养诗诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "223",
        "name": "五行生克赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "224",
        "name": "珞琭子消息赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "225",
        "name": "论八字撮要法",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "226",
        "name": "会命要说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷五 · 诗诀口诀"
      },
      {
        "num": "227",
        "name": "病药说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "228",
        "name": "雕枯旺弱四病说类",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "229",
        "name": "损益生长四药说类",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "230",
        "name": "动静说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "231",
        "name": "盖头说",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "232",
        "name": "玉井奥诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "233",
        "name": "气象篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "234",
        "name": "看命口诀",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "235",
        "name": "巫咸撮要",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "236",
        "name": "元理赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "237",
        "name": "明通赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "238",
        "name": "六神篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "239",
        "name": "金声玉振赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "240",
        "name": "一行禅师天元赋注解",
        "isDone": false,
        "hasSkill": false,
        "category": "卷六 · 高阶论法"
      },
      {
        "num": "241",
        "name": "崖泉摘锦",
        "isDone": false,
        "hasSkill": false,
        "category": "卷七 · 杂论补遗"
      },
      {
        "num": "242",
        "name": "渭泾篇",
        "isDone": false,
        "hasSkill": false,
        "category": "卷七 · 杂论补遗"
      },
      {
        "num": "243",
        "name": "女命大义",
        "isDone": false,
        "hasSkill": false,
        "category": "卷七 · 杂论补遗"
      },
      {
        "num": "244",
        "name": "讲命捷径赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷七 · 杂论补遗"
      },
      {
        "num": "245",
        "name": "金鼎神秘赋",
        "isDone": false,
        "hasSkill": false,
        "category": "卷七 · 杂论补遗"
      }
    ],
    "skills": [],
    "sources": [
      {
        "name": "爱憎赋"
      },
      {
        "name": "胞胎诗诀"
      },
      {
        "name": "宝法第二"
      },
      {
        "name": "宝法第一"
      },
      {
        "name": "碧渊赋"
      },
      {
        "name": "病药说"
      },
      {
        "name": "掣要捷驰玄妙诀"
      },
      {
        "name": "从革格"
      },
      {
        "name": "从革诗诀"
      },
      {
        "name": "寸金搜髓论"
      },
      {
        "name": "带疾诗诀"
      },
      {
        "name": "倒冲格"
      },
      {
        "name": "地支藏遁歌"
      },
      {
        "name": "帝旺诗诀"
      },
      {
        "name": "雕枯旺弱四病说类"
      },
      {
        "name": "动静说"
      },
      {
        "name": "飞天禄马格"
      },
      {
        "name": "飞天禄马诗诀"
      },
      {
        "name": "福德格诗诀"
      },
      {
        "name": "盖头说"
      },
      {
        "name": "拱贵格"
      },
      {
        "name": "拱禄格"
      },
      {
        "name": "拱禄拱贵诗诀"
      },
      {
        "name": "勾陈得位格"
      },
      {
        "name": "勾陈得位诗诀"
      },
      {
        "name": "冠带诗诀"
      },
      {
        "name": "归禄格"
      },
      {
        "name": "归禄格诗诀"
      },
      {
        "name": "合禄格"
      },
      {
        "name": "合禄诗诀"
      },
      {
        "name": "化气诗诀"
      },
      {
        "name": "化气十段锦"
      },
      {
        "name": "会命要说"
      },
      {
        "name": "继善篇"
      },
      {
        "name": "夹丘格"
      },
      {
        "name": "稼穑格"
      },
      {
        "name": "稼穑诗诀"
      },
      {
        "name": "讲命捷径赋"
      },
      {
        "name": "金鼎神秘赋"
      },
      {
        "name": "金神诗诀"
      },
      {
        "name": "金声玉振赋"
      },
      {
        "name": "金玉赋"
      },
      {
        "name": "井栏叉格"
      },
      {
        "name": "井栏叉格诗诀"
      },
      {
        "name": "看命口诀"
      },
      {
        "name": "克妻诗诀"
      },
      {
        "name": "克子诗诀"
      },
      {
        "name": "魁罡诗诀"
      },
      {
        "name": "两干不杂格"
      },
      {
        "name": "临官诗诀"
      },
      {
        "name": "六甲趋干格"
      },
      {
        "name": "六甲趋干诗诀"
      },
      {
        "name": "六亲捷要歌"
      },
      {
        "name": "六亲总论"
      },
      {
        "name": "六壬趋艮格"
      },
      {
        "name": "六壬趋艮诗诀"
      },
      {
        "name": "六神篇"
      },
      {
        "name": "六乙鼠贵格"
      },
      {
        "name": "六乙鼠贵诗诀"
      },
      {
        "name": "六阴朝阳格"
      },
      {
        "name": "六阴朝阳诗诀"
      },
      {
        "name": "论八字撮要法"
      },
      {
        "name": "论大运"
      },
      {
        "name": "论倒食"
      },
      {
        "name": "论福德秀气"
      },
      {
        "name": "论父"
      },
      {
        "name": "论妇人总诀"
      },
      {
        "name": "论干支字义"
      },
      {
        "name": "论官杀混杂要制伏"
      },
      {
        "name": "论官星太过"
      },
      {
        "name": "论华盖"
      },
      {
        "name": "论疾病"
      },
      {
        "name": "论劫财"
      },
      {
        "name": "论金神"
      },
      {
        "name": "论魁罡"
      },
      {
        "name": "论六甲空亡"
      },
      {
        "name": "论六十花甲子纳音并注解"
      },
      {
        "name": "论命细法"
      },
      {
        "name": "论母"
      },
      {
        "name": "论年上起月例"
      },
      {
        "name": "论偏财"
      },
      {
        "name": "论偏官即七杀"
      },
      {
        "name": "论七杀即偏官"
      },
      {
        "name": "论妻妾"
      },
      {
        "name": "论起大运法"
      },
      {
        "name": "论起玉堂天乙贵人"
      },
      {
        "name": "论日德"
      },
      {
        "name": "论日贵"
      },
      {
        "name": "论日刃"
      },
      {
        "name": "论日上起时例"
      },
      {
        "name": "论日为主"
      },
      {
        "name": "论三奇贵人"
      },
      {
        "name": "论三元"
      },
      {
        "name": "论伤官"
      },
      {
        "name": "论生旺"
      },
      {
        "name": "论十二地支阴阳所属"
      },
      {
        "name": "论十二支六合"
      },
      {
        "name": "论十二支三合"
      },
      {
        "name": "论十二支相冲"
      },
      {
        "name": "论十二支相穿"
      },
      {
        "name": "论十二支相刑"
      },
      {
        "name": "论十干禄"
      },
      {
        "name": "论时墓"
      },
      {
        "name": "论食神"
      },
      {
        "name": "论四大空亡"
      },
      {
        "name": "论太岁吉凶"
      },
      {
        "name": "论天德贵人"
      },
      {
        "name": "论天地干支暗藏总诀"
      },
      {
        "name": "论天地干支所出"
      },
      {
        "name": "论天干生旺死绝"
      },
      {
        "name": "论天罗地网"
      },
      {
        "name": "论天赦"
      },
      {
        "name": "论五行墓库财印"
      },
      {
        "name": "论五行生克制化各有所喜所害例"
      },
      {
        "name": "论五行所生之始"
      },
      {
        "name": "论五行相生相克"
      },
      {
        "name": "论小儿"
      },
      {
        "name": "论小儿关杀例"
      },
      {
        "name": "论刑合"
      },
      {
        "name": "论行小运法"
      },
      {
        "name": "论兴亡"
      },
      {
        "name": "论性情"
      },
      {
        "name": "论兄弟姐妹"
      },
      {
        "name": "论羊刃"
      },
      {
        "name": "论驿马"
      },
      {
        "name": "论印绶"
      },
      {
        "name": "论月德贵人"
      },
      {
        "name": "论月令"
      },
      {
        "name": "论运化气"
      },
      {
        "name": "论杂气"
      },
      {
        "name": "论正财"
      },
      {
        "name": "论子息"
      },
      {
        "name": "络绎赋"
      },
      {
        "name": "珞琭子消息赋"
      },
      {
        "name": "明通赋"
      },
      {
        "name": "沐浴诗诀"
      },
      {
        "name": "墓库诗诀"
      },
      {
        "name": "女命大义"
      },
      {
        "name": "女命富贵贫贱篇"
      },
      {
        "name": "女命诗诀"
      },
      {
        "name": "偏财诗诀"
      },
      {
        "name": "偏官诗诀"
      },
      {
        "name": "飘荡诗诀"
      },
      {
        "name": "气象篇"
      },
      {
        "name": "弃命从财格"
      },
      {
        "name": "弃命从财诗诀"
      },
      {
        "name": "弃命从杀格"
      },
      {
        "name": "弃命从杀论"
      },
      {
        "name": "弃命从杀诗诀"
      },
      {
        "name": "曲直格"
      },
      {
        "name": "曲直格诗诀"
      },
      {
        "name": "群兴论"
      },
      {
        "name": "人鉴论"
      },
      {
        "name": "壬骑龙背格"
      },
      {
        "name": "壬骑龙背诗诀"
      },
      {
        "name": "日德诗诀"
      },
      {
        "name": "日德秀气格"
      },
      {
        "name": "日贵诗诀"
      },
      {
        "name": "润下格"
      },
      {
        "name": "润下诗诀"
      },
      {
        "name": "杀重有救诗诀"
      },
      {
        "name": "伤官带杀格"
      },
      {
        "name": "伤官生财格"
      },
      {
        "name": "伤官诗诀"
      },
      {
        "name": "伤官说"
      },
      {
        "name": "身弱论"
      },
      {
        "name": "神趣八法-从象"
      },
      {
        "name": "神趣八法-返象"
      },
      {
        "name": "神趣八法-伏象"
      },
      {
        "name": "神趣八法-鬼象"
      },
      {
        "name": "神趣八法-化象"
      },
      {
        "name": "神趣八法-类象"
      },
      {
        "name": "神趣八法-属象"
      },
      {
        "name": "神趣八法-照象"
      },
      {
        "name": "十二支体象"
      },
      {
        "name": "十干所属方位十二支所属论"
      },
      {
        "name": "十干体象"
      },
      {
        "name": "时墓诗诀"
      },
      {
        "name": "时上偏财格"
      },
      {
        "name": "时上偏财诗诀"
      },
      {
        "name": "时上一位贵格"
      },
      {
        "name": "时上一位贵诗诀"
      },
      {
        "name": "食神诗诀"
      },
      {
        "name": "寿元诗诀"
      },
      {
        "name": "衰病死诗诀"
      },
      {
        "name": "四言独步"
      },
      {
        "name": "岁德扶财格"
      },
      {
        "name": "岁德扶杀格"
      },
      {
        "name": "损益生长四药说类"
      },
      {
        "name": "胎养诗诀"
      },
      {
        "name": "题记与引"
      },
      {
        "name": "天干五阳通变"
      },
      {
        "name": "天干五阴通变"
      },
      {
        "name": "天干相合"
      },
      {
        "name": "天元一气诗诀"
      },
      {
        "name": "万金赋"
      },
      {
        "name": "渭泾篇"
      },
      {
        "name": "巫咸撮要"
      },
      {
        "name": "五行俱足格"
      },
      {
        "name": "五行生克赋"
      },
      {
        "name": "五行元理消息赋"
      },
      {
        "name": "五言独步"
      },
      {
        "name": "喜忌篇"
      },
      {
        "name": "相心赋"
      },
      {
        "name": "详解定真论"
      },
      {
        "name": "心镜歌"
      },
      {
        "name": "刑冲诗诀"
      },
      {
        "name": "刑合格"
      },
      {
        "name": "刑合诗诀"
      },
      {
        "name": "玄机赋"
      },
      {
        "name": "玄武当权格"
      },
      {
        "name": "玄武当权诗诀"
      },
      {
        "name": "崖泉摘锦"
      },
      {
        "name": "炎上格"
      },
      {
        "name": "炎上格诗诀"
      },
      {
        "name": "羊刃诗诀"
      },
      {
        "name": "妖祥赋"
      },
      {
        "name": "一行禅师天元赋注解"
      },
      {
        "name": "阴命赋"
      },
      {
        "name": "印绶格"
      },
      {
        "name": "印绶诗诀"
      },
      {
        "name": "幽微赋"
      },
      {
        "name": "又论五行生旺衰绝吉凶"
      },
      {
        "name": "玉井奥诀"
      },
      {
        "name": "渊源集说"
      },
      {
        "name": "元理赋"
      },
      {
        "name": "月上偏官格"
      },
      {
        "name": "运晦诗诀"
      },
      {
        "name": "运通诗诀"
      },
      {
        "name": "杂论口诀"
      },
      {
        "name": "杂气财官格"
      },
      {
        "name": "杂气财官诗诀"
      },
      {
        "name": "杂气印绶格"
      },
      {
        "name": "造微论"
      },
      {
        "name": "长生诗诀"
      },
      {
        "name": "正财诗诀"
      },
      {
        "name": "正官格"
      },
      {
        "name": "正官论"
      },
      {
        "name": "正官诗诀"
      },
      {
        "name": "子平百章歌"
      },
      {
        "name": "子平举要歌"
      },
      {
        "name": "子遥巳格"
      },
      {
        "name": "子遥巳诗诀"
      }
    ]
  },
  {
    "slug": "滴天髓阐微",
    "section": "命",
    "category": "八字",
    "title": "滴天髓阐微",
    "author": "[明] 刘基 撰 / [清] 任铁樵 注",
    "version": "据《四库全书》本",
    "description": "子平命理学核心经典，以天干地支五行生克为核心，共六十一篇专题系统阐述命理原理",
    "total": 63,
    "done": 0,
    "chapters": [
      {
        "num": "01",
        "name": "天道",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "02",
        "name": "坤道",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "03",
        "name": "人道",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "04",
        "name": "知命",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "05",
        "name": "理气",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "06",
        "name": "配合",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "07",
        "name": "天干",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "08",
        "name": "地支",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "09",
        "name": "干支总论",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "10",
        "name": "形象",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "11",
        "name": "方局",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "12",
        "name": "八格",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "13",
        "name": "体用",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "14",
        "name": "精神",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "15",
        "name": "月令",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "16",
        "name": "生时",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "17",
        "name": "衰旺",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "18",
        "name": "中和",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "19",
        "name": "源流",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "20",
        "name": "通关",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "21",
        "name": "官杀",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "22",
        "name": "伤官",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "23",
        "name": "清气",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "24",
        "name": "浊气",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "25",
        "name": "真神",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "26",
        "name": "假神",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "27",
        "name": "刚柔",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "28",
        "name": "顺逆",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "29",
        "name": "寒暖",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "30",
        "name": "燥湿",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "31",
        "name": "隐显",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "32",
        "name": "众寡",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "33",
        "name": "震兑",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "34",
        "name": "坎离",
        "isDone": false,
        "hasSkill": false,
        "category": "上篇 · 通神论"
      },
      {
        "num": "35",
        "name": "夫妻",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "36",
        "name": "子女",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "37",
        "name": "父母",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "38",
        "name": "兄弟",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "39",
        "name": "何知",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "40",
        "name": "女命",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "41",
        "name": "小儿",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "42",
        "name": "才德",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "43",
        "name": "奋郁",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "44",
        "name": "恩怨",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "45",
        "name": "闲神",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "46",
        "name": "从象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "47",
        "name": "化象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "48",
        "name": "假从",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "49",
        "name": "假化",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "50",
        "name": "顺局",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "51",
        "name": "反局",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "52",
        "name": "战局",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "53",
        "name": "合局",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "54",
        "name": "君象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "55",
        "name": "臣象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "56",
        "name": "母象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "57",
        "name": "子象",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "58",
        "name": "性情",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "59",
        "name": "疾病",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "60",
        "name": "出身",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "61",
        "name": "地位",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "62",
        "name": "岁运",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "63",
        "name": "贞元",
        "isDone": false,
        "hasSkill": false,
        "category": "下篇 · 六亲论"
      }
    ],
    "skills": [],
    "sources": [
      {
        "name": "八格"
      },
      {
        "name": "才德"
      },
      {
        "name": "臣象"
      },
      {
        "name": "出身"
      },
      {
        "name": "从象"
      },
      {
        "name": "地位"
      },
      {
        "name": "地支"
      },
      {
        "name": "恩怨"
      },
      {
        "name": "反局"
      },
      {
        "name": "方局"
      },
      {
        "name": "奋郁"
      },
      {
        "name": "夫妻"
      },
      {
        "name": "父母"
      },
      {
        "name": "干支总论"
      },
      {
        "name": "刚柔"
      },
      {
        "name": "官杀"
      },
      {
        "name": "寒暖"
      },
      {
        "name": "合局"
      },
      {
        "name": "何知"
      },
      {
        "name": "化象"
      },
      {
        "name": "疾病"
      },
      {
        "name": "假从"
      },
      {
        "name": "假化"
      },
      {
        "name": "假神"
      },
      {
        "name": "精神"
      },
      {
        "name": "君象"
      },
      {
        "name": "坎离"
      },
      {
        "name": "坤道"
      },
      {
        "name": "理气"
      },
      {
        "name": "母象"
      },
      {
        "name": "女命"
      },
      {
        "name": "配合"
      },
      {
        "name": "清气"
      },
      {
        "name": "人道"
      },
      {
        "name": "伤官"
      },
      {
        "name": "生时"
      },
      {
        "name": "衰旺"
      },
      {
        "name": "顺局"
      },
      {
        "name": "顺逆"
      },
      {
        "name": "岁运"
      },
      {
        "name": "体用"
      },
      {
        "name": "天道"
      },
      {
        "name": "天干"
      },
      {
        "name": "通关"
      },
      {
        "name": "闲神"
      },
      {
        "name": "小儿"
      },
      {
        "name": "形象"
      },
      {
        "name": "性情"
      },
      {
        "name": "兄弟"
      },
      {
        "name": "隐显"
      },
      {
        "name": "源流"
      },
      {
        "name": "月令"
      },
      {
        "name": "燥湿"
      },
      {
        "name": "战局"
      },
      {
        "name": "贞元"
      },
      {
        "name": "真神"
      },
      {
        "name": "震兑"
      },
      {
        "name": "知命"
      },
      {
        "name": "中和"
      },
      {
        "name": "众寡"
      },
      {
        "name": "浊气"
      },
      {
        "name": "子女"
      },
      {
        "name": "子象"
      }
    ]
  },
  {
    "slug": "紫微斗数全书",
    "section": "命",
    "category": "紫微斗数",
    "title": "紫微斗数全书",
    "author": "[宋] 陈抟 撰",
    "version": "据《正统道藏》本",
    "description": "紫微斗数经典著作，托名宋初陈抟撰。包含太微赋、骨髓赋等核心赋文及安星诀法。",
    "total": 89,
    "done": 0,
    "chapters": [
      {
        "num": "01",
        "name": "羅序",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "02",
        "name": "太微賦",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "03",
        "name": "形性賦",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "04",
        "name": "星垣論",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "05",
        "name": "斗數準繩",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "06",
        "name": "斗數發微論",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "07",
        "name": "重補斗數彀率",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "08",
        "name": "增補太微賦",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "09",
        "name": "問紫微所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "10",
        "name": "問天機所主如何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "11",
        "name": "問太陽所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "12",
        "name": "問武曲星所主為何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "13",
        "name": "問天同星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "14",
        "name": "問廉貞所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "15",
        "name": "問天府所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "16",
        "name": "問太陰星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "17",
        "name": "問貪狼所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "18",
        "name": "問巨門所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "19",
        "name": "問天相星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "20",
        "name": "問天梁星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "21",
        "name": "問七殺星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "22",
        "name": "問破軍所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "23",
        "name": "問文昌星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "24",
        "name": "问文曲星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "25",
        "name": "问流年昌曲若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "26",
        "name": "问左辅所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "27",
        "name": "问右弼所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "28",
        "name": "问天魁天钺星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "29",
        "name": "问禄存星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "30",
        "name": "问天马星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "31",
        "name": "问化禄星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "32",
        "name": "问化权星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "33",
        "name": "问化科星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "34",
        "name": "问化忌星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "35",
        "name": "问擎羊星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "36",
        "name": "问陀罗星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "37",
        "name": "羊陀二星总论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "38",
        "name": "问火星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "39",
        "name": "问铃星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "40",
        "name": "羊陀火铃四星总论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "41",
        "name": "问天空地劫所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "42",
        "name": "问天伤天使所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "43",
        "name": "问天刑星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "44",
        "name": "问天姚星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "45",
        "name": "问天哭天虚二星所主若何？",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "46",
        "name": "斗数骨髓赋",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "47",
        "name": "女命骨髓赋",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "48",
        "name": "定富贵贫贱十等论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "49",
        "name": "十二宫诸星得地合格诀",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "50",
        "name": "十二宫诸星失陷破格诀",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "51",
        "name": "十二宫诸星得地富贵论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "52",
        "name": "十二宫诸星失陷贫贱论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "53",
        "name": "定富局",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "54",
        "name": "定贵局",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "55",
        "name": "定贫贱局",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "56",
        "name": "定杂局",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗數全書卷一"
      },
      {
        "num": "57",
        "name": "安身命例",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "58",
        "name": "命宫",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "59",
        "name": "兄弟",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "60",
        "name": "妻妾",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "61",
        "name": "子女",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "62",
        "name": "财帛",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "63",
        "name": "疾厄",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "64",
        "name": "迁移",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "65",
        "name": "奴仆",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "66",
        "name": "官禄",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "67",
        "name": "田宅",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "68",
        "name": "福德",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "69",
        "name": "父母",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷二"
      },
      {
        "num": "70",
        "name": "谈星要论",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "71",
        "name": "论人命入格",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "72",
        "name": "论格星数高下",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "73",
        "name": "论男女命同异",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "74",
        "name": "论小儿命",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "75",
        "name": "定小儿生时诀",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "76",
        "name": "论人生时安命吉凶",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "77",
        "name": "论人生时要审的确",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "78",
        "name": "论小儿克亲",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "79",
        "name": "论命先贫后富",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "80",
        "name": "论大限十年祸福何如",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "81",
        "name": "论二限太岁吉凶",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "82",
        "name": "论行限分南北斗",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "83",
        "name": "论流年太岁吉凶星杀",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "84",
        "name": "论阴骘延寿",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "85",
        "name": "论羊陀迭并",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "86",
        "name": "论七杀重逢",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "87",
        "name": "论大小限星辰过十二宫遇十二支所忌诀",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "88",
        "name": "论立命行限宫歌",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      },
      {
        "num": "89",
        "name": "论诸星同垣各司所宜分别富贵贫贱夭寿",
        "isDone": false,
        "hasSkill": false,
        "category": "紫微斗数全书卷三"
      }
    ],
    "skills": [],
    "sources": [
      {
        "name": "安身命例"
      },
      {
        "name": "定富贵贫贱十等论"
      },
      {
        "name": "定富局"
      },
      {
        "name": "定贵局"
      },
      {
        "name": "定贫贱局"
      },
      {
        "name": "定小儿生时诀"
      },
      {
        "name": "定杂局"
      },
      {
        "name": "斗数骨髓赋"
      },
      {
        "name": "斗數發微論"
      },
      {
        "name": "斗數準繩"
      },
      {
        "name": "论大限十年祸福何如"
      },
      {
        "name": "论大小限星辰过十二宫遇十二支所忌诀"
      },
      {
        "name": "论二限太岁吉凶"
      },
      {
        "name": "论格星数高下"
      },
      {
        "name": "论立命行限宫歌"
      },
      {
        "name": "论流年太岁吉凶星杀"
      },
      {
        "name": "论命先贫后富"
      },
      {
        "name": "论男女命同异"
      },
      {
        "name": "论七杀重逢"
      },
      {
        "name": "论人命入格"
      },
      {
        "name": "论人生时安命吉凶"
      },
      {
        "name": "论人生时要审的确"
      },
      {
        "name": "论小儿克亲"
      },
      {
        "name": "论小儿命"
      },
      {
        "name": "论行限分南北斗"
      },
      {
        "name": "论羊陀迭并"
      },
      {
        "name": "论阴骘延寿"
      },
      {
        "name": "论诸星同垣各司所宜分别富贵贫贱夭寿"
      },
      {
        "name": "羅序"
      },
      {
        "name": "女命骨髓赋"
      },
      {
        "name": "十二宫诸星得地富贵论"
      },
      {
        "name": "十二宫诸星得地合格诀"
      },
      {
        "name": "十二宫诸星失陷贫贱论"
      },
      {
        "name": "十二宫诸星失陷破格诀"
      },
      {
        "name": "太微賦"
      },
      {
        "name": "谈星要论"
      },
      {
        "name": "问化忌星所主若何？"
      },
      {
        "name": "问化科星所主若何？"
      },
      {
        "name": "问化禄星所主若何？"
      },
      {
        "name": "问化权星所主若何？"
      },
      {
        "name": "问火星所主若何？"
      },
      {
        "name": "问铃星所主若何？"
      },
      {
        "name": "问流年昌曲若何？"
      },
      {
        "name": "问禄存星所主若何？"
      },
      {
        "name": "问擎羊星所主若何？"
      },
      {
        "name": "问天空地劫所主若何？"
      },
      {
        "name": "问天哭天虚二星所主若何？"
      },
      {
        "name": "问天魁天钺星所主若何？"
      },
      {
        "name": "问天马星所主若何？"
      },
      {
        "name": "问天伤天使所主若何？"
      },
      {
        "name": "问天刑星所主若何？"
      },
      {
        "name": "问天姚星所主若何？"
      },
      {
        "name": "问陀罗星所主若何？"
      },
      {
        "name": "问文曲星所主若何？"
      },
      {
        "name": "问右弼所主若何？"
      },
      {
        "name": "问左辅所主若何？"
      },
      {
        "name": "問巨門所主若何？"
      },
      {
        "name": "問廉貞所主若何？"
      },
      {
        "name": "問破軍所主若何？"
      },
      {
        "name": "問七殺星所主若何？"
      },
      {
        "name": "問太陽所主若何？"
      },
      {
        "name": "問太陰星所主若何？"
      },
      {
        "name": "問貪狼所主若何？"
      },
      {
        "name": "問天府所主若何？"
      },
      {
        "name": "問天機所主如何？"
      },
      {
        "name": "問天梁星所主若何？"
      },
      {
        "name": "問天同星所主若何？"
      },
      {
        "name": "問天相星所主若何？"
      },
      {
        "name": "問文昌星所主若何？"
      },
      {
        "name": "問武曲星所主為何？"
      },
      {
        "name": "問紫微所主若何？"
      },
      {
        "name": "星垣論"
      },
      {
        "name": "形性賦"
      },
      {
        "name": "羊陀二星总论"
      },
      {
        "name": "羊陀火铃四星总论"
      },
      {
        "name": "增補太微賦"
      },
      {
        "name": "重補斗數彀率"
      }
    ]
  }
];
