// Auto-generated by scripts/generate.js — do not edit manually
import type { Book } from './book-types';

export const books: Book[] = [
  {
    "slug": "ditiansui-site",
    "section": "命",
    "title": "滴天髓阐微",
    "author": "[明] 刘基 撰 / [清] 任铁樵 注",
    "version": "据《四库全书》本",
    "description": "子平命理学核心经典，以天干地支五行生克为核心，通过六十余篇专题系统阐述命理原理。",
    "total": 63,
    "done": 63,
    "chapters": [
      {
        "num": "01",
        "name": "天道",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "02",
        "name": "坤道",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "03",
        "name": "人道",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "04",
        "name": "知命",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "05",
        "name": "理气",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "06",
        "name": "配合",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "07",
        "name": "天干",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "08",
        "name": "地支",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "09",
        "name": "干支总论",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "10",
        "name": "形象",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "11",
        "name": "方局",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "12",
        "name": "八格",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "13",
        "name": "体用",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "14",
        "name": "精神",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "15",
        "name": "月令",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "16",
        "name": "生时",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "17",
        "name": "衰旺",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "18",
        "name": "中和",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "19",
        "name": "源流",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "20",
        "name": "通关",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "21",
        "name": "官杀",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "22",
        "name": "伤官",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "23",
        "name": "清气",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "24",
        "name": "浊气",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "25",
        "name": "真神",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "26",
        "name": "假神",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "27",
        "name": "刚柔",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "28",
        "name": "顺逆",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "29",
        "name": "寒暖",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "30",
        "name": "燥湿",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "31",
        "name": "隐显",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "32",
        "name": "众寡",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "33",
        "name": "震兑",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "34",
        "name": "坎离",
        "isDone": true,
        "category": "上篇 · 通神论"
      },
      {
        "num": "35",
        "name": "夫妻",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "36",
        "name": "子女",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "37",
        "name": "父母",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "38",
        "name": "兄弟",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "39",
        "name": "何知",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "40",
        "name": "女命",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "41",
        "name": "小儿",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "42",
        "name": "才德",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "43",
        "name": "奋郁",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "44",
        "name": "恩怨",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "45",
        "name": "闲神",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "46",
        "name": "从象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "47",
        "name": "化象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "48",
        "name": "假从",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "49",
        "name": "假化",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "50",
        "name": "顺局",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "51",
        "name": "反局",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "52",
        "name": "战局",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "53",
        "name": "合局",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "54",
        "name": "君象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "55",
        "name": "臣象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "56",
        "name": "母象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "57",
        "name": "子象",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "58",
        "name": "性情",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "59",
        "name": "疾病",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "60",
        "name": "出身",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "61",
        "name": "地位",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "62",
        "name": "岁运",
        "isDone": true,
        "category": "下篇 · 六亲论"
      },
      {
        "num": "63",
        "name": "贞元",
        "isDone": true,
        "category": "下篇 · 六亲论"
      }
    ],
    "skills": [
      {
        "name": "bage"
      },
      {
        "name": "caide"
      },
      {
        "name": "chenxiang"
      },
      {
        "name": "chushen"
      },
      {
        "name": "congxiang"
      },
      {
        "name": "diwei"
      },
      {
        "name": "dizhi"
      },
      {
        "name": "enyuan"
      },
      {
        "name": "fangju"
      },
      {
        "name": "fanju"
      },
      {
        "name": "fenyu"
      },
      {
        "name": "fumu"
      },
      {
        "name": "fuqi"
      },
      {
        "name": "gangrou"
      },
      {
        "name": "ganzhi"
      },
      {
        "name": "guansha"
      },
      {
        "name": "hannuan"
      },
      {
        "name": "heju"
      },
      {
        "name": "hezhi"
      },
      {
        "name": "huaxiang"
      },
      {
        "name": "jiacong"
      },
      {
        "name": "jiahua"
      },
      {
        "name": "jiashen"
      },
      {
        "name": "jibing"
      },
      {
        "name": "jingshen"
      },
      {
        "name": "junxiang"
      },
      {
        "name": "kanli"
      },
      {
        "name": "kundao"
      },
      {
        "name": "liqi"
      },
      {
        "name": "muxiang"
      },
      {
        "name": "nvming"
      },
      {
        "name": "peihe"
      },
      {
        "name": "qingqi"
      },
      {
        "name": "rendao"
      },
      {
        "name": "shangguan"
      },
      {
        "name": "shengshi"
      },
      {
        "name": "shuaiwang"
      },
      {
        "name": "shunju"
      },
      {
        "name": "shunni"
      },
      {
        "name": "suiyun"
      },
      {
        "name": "tiandao"
      },
      {
        "name": "tiangan"
      },
      {
        "name": "tiyong"
      },
      {
        "name": "tongguan"
      },
      {
        "name": "xiangxing"
      },
      {
        "name": "xianshen"
      },
      {
        "name": "xiaoer"
      },
      {
        "name": "xingqing"
      },
      {
        "name": "xiongdi"
      },
      {
        "name": "yinxian"
      },
      {
        "name": "yuanliu"
      },
      {
        "name": "yueling"
      },
      {
        "name": "zaoshi"
      },
      {
        "name": "zhanju"
      },
      {
        "name": "zhendui"
      },
      {
        "name": "zhenshen"
      },
      {
        "name": "zhenyuan"
      },
      {
        "name": "zhiming"
      },
      {
        "name": "zhonggua"
      },
      {
        "name": "zhonghe"
      },
      {
        "name": "zhuoqi"
      },
      {
        "name": "zinv"
      },
      {
        "name": "zixiang"
      }
    ],
    "sources": [
      {
        "name": "八格"
      },
      {
        "name": "才德"
      },
      {
        "name": "臣象"
      },
      {
        "name": "出身"
      },
      {
        "name": "从象"
      },
      {
        "name": "地位"
      },
      {
        "name": "地支"
      },
      {
        "name": "恩怨"
      },
      {
        "name": "反局"
      },
      {
        "name": "方局"
      },
      {
        "name": "奋郁"
      },
      {
        "name": "夫妻"
      },
      {
        "name": "父母"
      },
      {
        "name": "干支总论"
      },
      {
        "name": "刚柔"
      },
      {
        "name": "官杀"
      },
      {
        "name": "寒暖"
      },
      {
        "name": "合局"
      },
      {
        "name": "何知"
      },
      {
        "name": "化象"
      },
      {
        "name": "疾病"
      },
      {
        "name": "假从"
      },
      {
        "name": "假化"
      },
      {
        "name": "假神"
      },
      {
        "name": "精神"
      },
      {
        "name": "君象"
      },
      {
        "name": "坎离"
      },
      {
        "name": "坤道"
      },
      {
        "name": "理气"
      },
      {
        "name": "母象"
      },
      {
        "name": "女命"
      },
      {
        "name": "配合"
      },
      {
        "name": "清气"
      },
      {
        "name": "人道"
      },
      {
        "name": "伤官"
      },
      {
        "name": "生时"
      },
      {
        "name": "衰旺"
      },
      {
        "name": "顺局"
      },
      {
        "name": "顺逆"
      },
      {
        "name": "岁运"
      },
      {
        "name": "体用"
      },
      {
        "name": "天道"
      },
      {
        "name": "天干"
      },
      {
        "name": "通关"
      },
      {
        "name": "闲神"
      },
      {
        "name": "小儿"
      },
      {
        "name": "形象"
      },
      {
        "name": "性情"
      },
      {
        "name": "兄弟"
      },
      {
        "name": "隐显"
      },
      {
        "name": "源流"
      },
      {
        "name": "月令"
      },
      {
        "name": "燥湿"
      },
      {
        "name": "战局"
      },
      {
        "name": "贞元"
      },
      {
        "name": "真神"
      },
      {
        "name": "震兑"
      },
      {
        "name": "知命"
      },
      {
        "name": "中和"
      },
      {
        "name": "众寡"
      },
      {
        "name": "浊气"
      },
      {
        "name": "子女"
      },
      {
        "name": "子象"
      }
    ]
  }
];
