// Auto-generated by scripts/generate.js — do not edit manually
export interface ChapterInfo {
  num: string;
  name: string;
  isDone: boolean;
}

export interface Book {
  slug: string;
  title: string;
  total: number;
  done: number;
  chapters: ChapterInfo[];
  skills: { name: string }[];
}

export const books: Book[] = [
  {
    "slug": "di-tian-sui",
    "title": "滴天髓阐微",
    "total": 64,
    "done": 9,
    "chapters": [
      {
        "num": "01",
        "name": "天道",
        "isDone": true
      },
      {
        "num": "02",
        "name": "坤道",
        "isDone": true
      },
      {
        "num": "03",
        "name": "人道",
        "isDone": true
      },
      {
        "num": "04",
        "name": "知命",
        "isDone": true
      },
      {
        "num": "05",
        "name": "理气",
        "isDone": true
      },
      {
        "num": "06",
        "name": "配合",
        "isDone": true
      },
      {
        "num": "07",
        "name": "天干",
        "isDone": true
      },
      {
        "num": "08",
        "name": "地支",
        "isDone": true
      },
      {
        "num": "09",
        "name": "干支总论",
        "isDone": false
      },
      {
        "num": "10",
        "name": "形象",
        "isDone": false
      },
      {
        "num": "11",
        "name": "方局",
        "isDone": false
      },
      {
        "num": "12",
        "name": "八格",
        "isDone": true
      },
      {
        "num": "13",
        "name": "体用",
        "isDone": false
      },
      {
        "num": "14",
        "name": "精神",
        "isDone": false
      },
      {
        "num": "15",
        "name": "月令",
        "isDone": false
      },
      {
        "num": "16",
        "name": "生时",
        "isDone": false
      },
      {
        "num": "17",
        "name": "衰旺",
        "isDone": false
      },
      {
        "num": "18",
        "name": "中和",
        "isDone": false
      },
      {
        "num": "19",
        "name": "源流",
        "isDone": false
      },
      {
        "num": "20",
        "name": "通关",
        "isDone": false
      },
      {
        "num": "21",
        "name": "官杀",
        "isDone": false
      },
      {
        "num": "22",
        "name": "伤官",
        "isDone": false
      },
      {
        "num": "23",
        "name": "清气",
        "isDone": false
      },
      {
        "num": "24",
        "name": "浊气",
        "isDone": false
      },
      {
        "num": "25",
        "name": "真神",
        "isDone": false
      },
      {
        "num": "26",
        "name": "假神",
        "isDone": false
      },
      {
        "num": "27",
        "name": "刚柔",
        "isDone": false
      },
      {
        "num": "28",
        "name": "顺逆",
        "isDone": false
      },
      {
        "num": "29",
        "name": "寒暖",
        "isDone": false
      },
      {
        "num": "30",
        "name": "燥湿",
        "isDone": false
      },
      {
        "num": "31",
        "name": "隐显",
        "isDone": false
      },
      {
        "num": "32",
        "name": "众寡",
        "isDone": false
      },
      {
        "num": "33",
        "name": "震兑",
        "isDone": false
      },
      {
        "num": "34",
        "name": "坎离",
        "isDone": false
      },
      {
        "num": "35",
        "name": "夫妻",
        "isDone": false
      },
      {
        "num": "36",
        "name": "子女",
        "isDone": false
      },
      {
        "num": "37",
        "name": "父母",
        "isDone": false
      },
      {
        "num": "38",
        "name": "兄弟",
        "isDone": false
      },
      {
        "num": "39",
        "name": "何知",
        "isDone": false
      },
      {
        "num": "40",
        "name": "女命",
        "isDone": false
      },
      {
        "num": "41",
        "name": "小儿",
        "isDone": false
      },
      {
        "num": "42",
        "name": "才德",
        "isDone": false
      },
      {
        "num": "43",
        "name": "奋郁",
        "isDone": false
      },
      {
        "num": "44",
        "name": "恩怨",
        "isDone": false
      },
      {
        "num": "45",
        "name": "闲神",
        "isDone": false
      },
      {
        "num": "46",
        "name": "从象",
        "isDone": false
      },
      {
        "num": "47",
        "name": "化象",
        "isDone": false
      },
      {
        "num": "48",
        "name": "假从",
        "isDone": false
      },
      {
        "num": "49",
        "name": "假化",
        "isDone": false
      },
      {
        "num": "50",
        "name": "顺局",
        "isDone": false
      },
      {
        "num": "51",
        "name": "反局",
        "isDone": false
      },
      {
        "num": "52",
        "name": "战局",
        "isDone": false
      },
      {
        "num": "53",
        "name": "合局",
        "isDone": false
      },
      {
        "num": "54",
        "name": "君象",
        "isDone": false
      },
      {
        "num": "55",
        "name": "臣象",
        "isDone": false
      },
      {
        "num": "56",
        "name": "母象",
        "isDone": false
      },
      {
        "num": "57",
        "name": "子象",
        "isDone": false
      },
      {
        "num": "58",
        "name": "性情",
        "isDone": false
      },
      {
        "num": "59",
        "name": "疾病",
        "isDone": false
      },
      {
        "num": "60",
        "name": "出身",
        "isDone": false
      },
      {
        "num": "61",
        "name": "地位",
        "isDone": false
      },
      {
        "num": "62",
        "name": "岁运",
        "isDone": false
      },
      {
        "num": "63",
        "name": "真元",
        "isDone": false
      },
      {
        "num": "64",
        "name": "六亲总论",
        "isDone": false
      }
    ],
    "skills": [
      {
        "name": "bage"
      },
      {
        "name": "dizhi"
      },
      {
        "name": "kundao"
      },
      {
        "name": "liqi"
      },
      {
        "name": "peihe"
      },
      {
        "name": "rendao"
      },
      {
        "name": "tiandao"
      },
      {
        "name": "tiangan"
      },
      {
        "name": "zhiming"
      }
    ]
  }
];
